name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  update_portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger "Deploy" workflow in "Portfolio" repository
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/pd-escher/portfolio/dispatches \
          -d '{"event_type":"update_blogs"}'
